INSERT INTO mapping.canonical_field(canonical_path, semantic_domain, definition, datatype, cardinality, standard_uri) VALUES
('legal_entity.entity_class','identity','Canonical class of the registered economic subject.','text','1','https://semiceu.github.io/Core-Business-Vocabulary/'),
('legal_entity.legal_form','identity','Legal form under an external or national legal-form vocabulary.','text','0..1','https://semiceu.github.io/Core-Business-Vocabulary/'),
('legal_entity.registration_country','identity','Country in which the subject is registered, when known.','char(2)','0..1','https://semiceu.github.io/Core-Business-Vocabulary/'),
('entity_name.name','identity','Source-supported canonical name of the legal entity.','text','1..n','https://semiceu.github.io/Core-Business-Vocabulary/'),
('entity_identifier.value','identity','Value of an external identifier.','text','0..n','http://www.w3.org/ns/adms#Identifier'),
('entity_identifier.scheme','identity','Identifier scheme such as IT_CF or IT_VAT.','text','0..n','http://www.w3.org/ns/adms#Identifier'),
('establishment.type','location','Role/type of an establishment.','text','0..n',NULL),
('establishment.address','location','Canonical address associated with an establishment.','object','0..n','http://www.w3.org/ns/locn#Address'),
('relationship_state.administrative_disposition','whitelist','Administrative disposition explicitly supported by evidence.','text','0..1',NULL),
('relationship_state.legal_effect_status','whitelist','Whether the White List relationship is legally effective for the represented interval.','text','1',NULL),
('relationship_state.nominal_valid_from','whitelist','Nominal start date printed or asserted for an enrolment.','date','0..1',NULL),
('relationship_state.nominal_valid_until','whitelist','Nominal expiry date printed or asserted by the source.','date','0..1',NULL),
('relationship_sector.sector_concept','whitelist','Canonical White List activity concept associated with the relationship.','uuid','0..n','http://www.w3.org/2004/02/skos/core#Concept'),
('relationship_sector.scheme_membership','whitelist','Versioned scheme membership/notation used by the applicable White List taxonomy.','uuid','0..n','http://www.w3.org/2004/02/skos/core#ConceptScheme'),
('procedure.type','procedure','Type of administrative White List procedure.','text','1',NULL),
('procedure.official_identifier','procedure','Official procedure/protocol identifier when published.','text','0..1',NULL),
('procedure.application_date','procedure','Date on which the application was submitted, when known.','date','0..1',NULL),
('procedure.decision_date','procedure','Date of the administrative decision, when known.','date','0..1',NULL),
('procedure.status','procedure','Observed/canonical procedure status.','text','1',NULL),
('procedure.outcome','procedure','Outcome of a completed procedure, when known.','text','0..1',NULL),
('source.reference_period','source','Period/date to which a source edition explicitly or inferentially refers.','daterange','0..1','http://purl.org/dc/terms/temporal'),
('source.raw_value','source','Immutable literal value extracted from a source field.','text','0..n',NULL)
ON CONFLICT (canonical_path) DO NOTHING;

INSERT INTO mapping.canonical_field(canonical_path, semantic_domain, definition, datatype, cardinality, standard_uri) VALUES
('entity_name.language','identity','BCP 47 language tag for the canonical entity name.','text','1','http://purl.org/dc/terms/language'),
('entity_name.effective_period','temporal','Administrative/world-time applicability of the entity name, when known.','daterange','0..1',NULL),
('entity_name.observation_period','temporal','Interval during which acquired sources support this entity-name assertion.','tstzrange','1',NULL),
('entity_name.system_period','temporal','Interval during which this row is the archive canonical representation.','tstzrange','1',NULL),
('public_authority.identifier','authority','Official identifier of the public authority when known.','text','0..n',NULL),
('public_authority.jurisdiction','authority','Temporal jurisdiction assigned to the public authority.','object','0..n','https://semiceu.github.io/CPOV/'),
('white_list_regime.code','whitelist','Stable internal identifier of a White List legal/administrative regime.','text','1',NULL),
('white_list_register.id','whitelist','Canonical identifier of a concrete administrative White List register.','uuid','1',NULL),
('white_list_register.authority','whitelist','Public authority maintaining the White List register.','uuid','1','https://semiceu.github.io/CPOV/'),
('relationship.id','whitelist','Stable canonical relationship between a legal entity and a White List register.','uuid','1',NULL),
('relationship_state.effective_period','temporal','World/administrative time represented by a relationship-state version, when determinable.','daterange','0..1',NULL),
('relationship_state.observation_period','temporal','Interval during which acquired sources support a relationship-state version.','tstzrange','1',NULL),
('relationship_state.system_period','temporal','Interval during which a relationship-state version is the archive representation.','tstzrange','1',NULL),
('relationship_sector.listing_status','whitelist','Canonical listing status of a sector associated with a White List relationship.','text','1',NULL),
('sector_scheme.version','whitelist','Version of the legal White List sector classification used to interpret a source notation.','uuid','0..1','http://www.w3.org/2004/02/skos/core#ConceptScheme'),
('procedure.effective_period','temporal','Administrative/world-time interval represented by a procedure version, when determinable.','daterange','0..1',NULL),
('procedure.observation_period','temporal','Interval during which acquired sources support a procedure version.','tstzrange','1',NULL),
('procedure.system_period','temporal','Interval during which a procedure version is the archive representation.','tstzrange','1',NULL),
('source.series','source','Stable recurring source series from an authority or register.','uuid','0..1',NULL),
('source.edition','source','Logical source edition identified explicitly or inferentially.','uuid','0..1',NULL),
('source.capture','source','A timestamped acquisition of a source resource.','uuid','0..n','http://www.w3.org/ns/prov#Entity'),
('source.origin_type','source','Classification of source origin at capture time.','text','1',NULL),
('source.authority_rank','source','Evidential authority rank assigned to a source capture.','text','1',NULL),
('source.content_sha256','source','SHA-256 digest identifying immutable acquired bytes.','text','1',NULL),
('resolution.entity_decision','provenance','Auditable decision linking an entity mention to a canonical legal entity.','object','0..n','http://www.w3.org/ns/prov#Activity'),
('resolution.procedure_decision','provenance','Auditable decision linking a procedure mention to a canonical procedure.','object','0..n','http://www.w3.org/ns/prov#Activity'),
('provenance.processing_activity','provenance','Versioned activity that generated or transformed a canonical assertion.','uuid','1','http://www.w3.org/ns/prov#Activity')
ON CONFLICT (canonical_path) DO NOTHING;
