// CI acceptance test of the actual Pages artifact, served over HTTP.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const registry=JSON.parse(fs.readFileSync('public-site/data/registry.json'));
const {displayDate,publicStatistics}=require('../public-site/summary.js');
const numeric=text=>Number(text.replace(/\D/g,''));
const statusCounts=records=>Object.fromEntries([...records.reduce((m,r)=>m.set(r.source_status,(m.get(r.source_status)||0)+1),new Map())].sort());

(async()=>{
  fs.mkdirSync('test-results',{recursive:true});
  const browser=await chromium.launch();
  try {
    for(const width of [1440,390]){
      const page=await browser.newPage({viewport:{width,height:900}});
      const errors=[];page.on('pageerror',e=>errors.push(e.message));
      await page.goto('http://127.0.0.1:8765/');
      await page.locator('#status').filter({hasText:'Registro caricato'}).waitFor();
      assert.equal(await page.locator('#reg-status').inputValue(),'listed');
      const labels=await page.locator('#reg-register option').allTextContents();
      assert.equal(labels.length,new Set(labels).size);
      assert.ok(labels.includes('White List ordinaria · Prefettura di Cosenza'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Parma'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Pistoia'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Alessandria'));
      assert.ok(labels.includes("White List ordinaria · Regione autonoma Valle d'Aosta · funzioni prefettizie"));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Arezzo'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Avellino'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Pesaro e Urbino'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Biella'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Benevento'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Asti'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Agrigento'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Belluno'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Ascoli Piceno'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Ancona'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Bari'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Udine'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Bergamo'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Barletta-Andria-Trani'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Brindisi'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Cagliari'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Caltanissetta'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Crotone'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Campobasso'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Brescia'));
      assert.ok(labels.includes('White List ordinaria · Commissariato del Governo per la Provincia di Bolzano'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Caserta'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Catania'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Genova'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Foggia'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Forlì-Cesena'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Frosinone'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Gorizia'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Napoli'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Padova'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Perugia'));
      assert.ok(labels.includes('White List ordinaria · Commissariato del Governo per la Provincia di Trento'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Lodi'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Roma'));
      assert.ok(labels.includes('White List — Prefettura di Pisa · Prefettura di Pisa'));
      assert.ok(labels.includes('White List — Prefettura di Catanzaro · Prefettura di Catanzaro'));
      assert.ok(labels.includes('White List — Prefettura di Lecco · Prefettura di Lecco'));
      assert.ok(labels.includes('White List — Prefettura di Torino · Prefettura di Torino'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Potenza'));
      assert.ok(labels.includes('White List — Prefettura di Sassari · Prefettura di Sassari'));
      assert.ok(labels.includes('White List — Prefettura di Milano · Prefettura di Milano'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Como'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Firenze'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Taranto'));
      assert.ok(labels.includes('White List ordinaria · Prefettura di Lecce'));
      assert.ok(labels.includes('White List provinciale · Prefettura di Modena'));
      assert.ok(labels.includes('White List post-sisma · Prefettura di Modena'));
      assert.ok(!(await page.locator('#view-registry tbody').innerText()).match(/\b\d{4}-\d{2}-\d{2}\b/));
      assert.equal(numeric(await page.locator('#view-registry .section-title').last().innerText()),registry.records.filter(r=>r.source_status==='listed').length);
      assert.equal(numeric((await page.locator('.public-banner').first().innerText()).match(/([\d.,]+) presenze/)[1]),registry.records.length);
      await page.screenshot({path:`test-results/registry-${width}.png`});
      const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
      assert.equal(overflow,false,`Unexpected outer horizontal overflow at ${width}px`);
      // Keep explicit table scrolling; do not drop company columns on mobile.
      assert.equal(await page.locator('#view-registry th').count(),9);
      await page.locator('#reg-authority').selectOption('cosenza');
      await page.locator('#reg-status').selectOption('pending');
      const pending=registry.records.filter(r=>r.authority_key==='cosenza'&&r.source_status==='pending');
      assert.equal(numeric(await page.locator('#view-registry .section-title').last().innerText()),pending.length);
      await page.locator('#reg-q').pressSequentially('zzzz_no_company');
      assert.equal(await page.locator('#reg-q').inputValue(),'zzzz_no_company');
      assert.equal(await page.locator('#view-registry tbody').innerText(),'Nessun risultato.');
      await page.locator('#reg-q').fill('');
      await page.locator('#reg-status').selectOption('listed');
      const row=page.locator('#view-registry .clickrow').first();
      const locator=await row.getAttribute('data-record');
      const expected=registry.records.find(r=>r.record_locator===locator);
      await row.press('Enter');
      await page.locator('#detail.open').waitFor();
      assert.equal(await page.locator('#detail-title').innerText(),expected.name);
      assert.ok((await page.locator('#detail-body').innerText()).includes(displayDate(expected.reference_date)));
      assert.equal(await page.getByRole('link',{name:'Consulta l’elenco ufficiale',exact:true}).first().getAttribute('href'),expected.resource_url);
      await page.screenshot({path:`test-results/detail-${width}.png`});
      await page.keyboard.press('Escape');
      assert.equal(await page.locator('#detail').getAttribute('aria-hidden'),'true');
      for(const [name,id] of [['Statistiche','statistics'],['Prefetture','prefectures'],['Storico','history'],['Metodo e fonti','method'],['Qualità dei dati','quality']]){
        await page.getByRole('button',{name,exact:true}).click();
        await page.locator(`#view-${id}.active`).waitFor();
        const body=await page.locator(`#view-${id}`).innerText();
        for(const forbidden of ['canonical population','candidate precision','schema_fingerprint','scope ancora incompleto','review_notes','table_catalog'])assert.ok(!body.includes(forbidden));
        assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
        await page.screenshot({path:`test-results/${id}-${width}.png`,fullPage:id==='statistics'});
      }
      await page.getByRole('button',{name:'Statistiche',exact:true}).click();
      const stats=publicStatistics(registry.records);
      // Freeze the pre-expansion four-Prefecture baseline independently of later
      // authorities, then assert each added authority and the current total.
      assert.equal(stats.total,60557);
      const previous=registry.records.filter(r=>!['alessandria','aosta','arezzo','avellino','pesaro-e-urbino','biella','benevento','asti','agrigento','belluno','ascoli-piceno','ancona','bari','udine','bergamo','barletta-andria-trani','brindisi','cagliari','caltanissetta','crotone','campobasso','brescia','bolzano-bozen','caserta','catania','genova','foggia','forli-cesena','frosinone','gorizia','napoli','padova','perugia','trento','lodi','roma','pisa','catanzaro','lecco','torino','potenza','sassari','milano','modena','como','firenze','taranto','lecce'].includes(r.authority_key));
      assert.equal(previous.length,5052);
      assert.deepEqual(statusCounts(previous),{
        cancellation_related:2,expired_observed:171,listed:2229,other_or_unknown:5,
        pending:1416,rejected_or_denied:12,renewal_requested:14,renewal_update_in_progress:1203
      });
      const como=registry.records.filter(r=>r.authority_key==='como');
      assert.equal(como.length,409);
      assert.equal(como.filter(r=>r.source_key==='como-listed').length,391);
      assert.equal(como.filter(r=>r.source_key==='como-applicants').length,18);
      assert.deepEqual(statusCounts(como),{listed:359,pending:18,renewal_update_in_progress:32});
      const firenze=registry.records.filter(r=>r.authority_key==='firenze');
      assert.equal(firenze.length,664);
      assert.equal(firenze.filter(r=>r.source_key==='firenze-listed').length,539);
      assert.equal(firenze.filter(r=>r.source_key==='firenze-applicants').length,125);
      assert.deepEqual(statusCounts(firenze),{listed:429,pending:125,renewal_update_in_progress:110});
      assert.equal(new Set(firenze.map(r=>r.record_locator)).size,664);
      assert.equal(firenze.filter(r=>r.identifiers.length>0).length,660);
      assert.equal(firenze.filter(r=>r.identifier_field_raw&&r.identifiers.length===0).length,4);
      assert.equal(firenze.filter(r=>r.source_key==='firenze-applicants'&&!r.registered_office).length,2);
      const taranto=registry.records.filter(r=>r.authority_key==='taranto');
      assert.equal(taranto.length,600);
      assert.equal(taranto.filter(r=>r.source_key==='taranto-listed').length,388);
      assert.equal(taranto.filter(r=>r.source_key==='taranto-applicants').length,212);
      assert.deepEqual(statusCounts(taranto),{listed:212,pending:212,renewal_update_in_progress:176});
      assert.equal(new Set(taranto.map(r=>r.record_locator)).size,600);
      assert.equal(taranto.filter(r=>r.identifiers.length>0).length,592);
      assert.equal(taranto.filter(r=>r.identifier_field_raw&&r.identifiers.length===0).length,8);
      assert.equal(taranto.filter(r=>r.source_key==='taranto-listed'&&r.source_fields.malformed_date_pairs.length>0).length,8);
      const lecce=registry.records.filter(r=>r.authority_key==='lecce');
      assert.equal(lecce.length,915);
      assert.equal(lecce.filter(r=>r.source_key==='lecce-listed').length,825);
      assert.equal(lecce.filter(r=>r.source_key==='lecce-applicants').length,90);
      assert.deepEqual(statusCounts(lecce),{listed:582,pending:90,renewal_update_in_progress:243});
      assert.equal(new Set(lecce.map(r=>r.record_locator)).size,915);
      assert.equal(lecce.filter(r=>r.identifiers.length>0).length,894);
      assert.equal(lecce.filter(r=>r.identifier_field_raw&&r.identifiers.length===0).length,20);
      assert.equal(lecce.filter(r=>!r.identifier_field_raw&&r.identifiers.length===0).length,1);
      assert.equal(lecce.filter(r=>r.source_key==='lecce-listed'&&!r.observed_listing_date&&r.source_fields.listing_date_raw_variants.length>0).length,4);
      assert.equal(lecce.filter(r=>r.source_key==='lecce-listed'&&!r.observed_expiry_date&&r.source_fields.expiry_date_raw_variants.length>0).length,2);
      const alessandria=registry.records.filter(r=>r.authority_key==='alessandria');
      assert.equal(alessandria.length,434);
      assert.equal(alessandria.filter(r=>r.source_key==='alessandria-listed').length,363);
      assert.equal(alessandria.filter(r=>r.source_key==='alessandria-applicants').length,71);
      const aosta=registry.records.filter(r=>r.authority_key==='aosta');
      assert.equal(aosta.length,382);
      assert.equal(aosta.filter(r=>r.source_key==='aosta-listed').length,241);
      assert.equal(aosta.filter(r=>r.source_key==='aosta-applicants').length,141);
      assert.deepEqual(statusCounts(aosta),{listed:335,pending:26,renewal_update_in_progress:21});
      const arezzo=registry.records.filter(r=>r.authority_key==='arezzo');
      assert.equal(arezzo.length,364);
      assert.equal(arezzo.filter(r=>r.source_key==='arezzo-listed').length,332);
      assert.equal(arezzo.filter(r=>r.source_key==='arezzo-applicants').length,32);
      assert.deepEqual(statusCounts(arezzo),{listed:288,pending:32,renewal_update_in_progress:44});
      const avellino=registry.records.filter(r=>r.authority_key==='avellino');
      assert.equal(avellino.length,627);
      assert.equal(avellino.filter(r=>r.source_key==='avellino-listed').length,383);
      assert.equal(avellino.filter(r=>r.source_key==='avellino-applicants').length,244);
      assert.deepEqual(statusCounts(avellino),{listed:383,pending:244});
      const pesaro=registry.records.filter(r=>r.authority_key==='pesaro-e-urbino');
      assert.equal(pesaro.length,484);
      assert.equal(pesaro.filter(r=>r.source_key==='pesaro-urbino-combined').length,484);
      assert.deepEqual(statusCounts(pesaro),{listed:406,renewal_update_in_progress:78});
      const biella=registry.records.filter(r=>r.authority_key==='biella');
      assert.equal(biella.length,239);
      assert.equal(biella.filter(r=>r.source_key==='biella-listed').length,130);
      assert.equal(biella.filter(r=>r.source_key==='biella-applicants').length,109);
      assert.deepEqual(statusCounts(biella),{listed:213,pending:12,renewal_update_in_progress:14});
      const benevento=registry.records.filter(r=>r.authority_key==='benevento');
      assert.equal(benevento.length,938);
      assert.equal(benevento.filter(r=>r.source_key==='benevento-listed').length,734);
      assert.equal(benevento.filter(r=>r.source_key==='benevento-applicants').length,204);
      assert.deepEqual(statusCounts(benevento),{listed:734,pending:204});
      const asti=registry.records.filter(r=>r.authority_key==='asti');
      assert.equal(asti.length,301);
      assert.equal(asti.filter(r=>r.source_key==='asti-listed').length,284);
      assert.equal(asti.filter(r=>r.source_key==='asti-applicants').length,17);
      assert.deepEqual(statusCounts(asti),{listed:287,other_or_unknown:1,pending:13});
      const agrigento=registry.records.filter(r=>r.authority_key==='agrigento');
      assert.equal(agrigento.length,1161);
      assert.equal(agrigento.filter(r=>r.source_key==='agrigento-listed').length,855);
      assert.equal(agrigento.filter(r=>r.source_key==='agrigento-applicants').length,306);
      const belluno=registry.records.filter(r=>r.authority_key==='belluno');
      assert.equal(belluno.length,402);
      assert.equal(belluno.filter(r=>r.source_key==='belluno-combined').length,402);
      assert.deepEqual(statusCounts(belluno),{expired_observed:49,listed:281,pending:10,renewal_update_in_progress:62});
      const ascoli=registry.records.filter(r=>r.authority_key==='ascoli-piceno');
      assert.equal(ascoli.length,601);
      assert.equal(ascoli.filter(r=>r.source_key==='ascoli-piceno-listed').length,544);
      assert.equal(ascoli.filter(r=>r.source_key==='ascoli-piceno-applicants').length,57);
      assert.deepEqual(statusCounts(ascoli),{listed:448,pending:57,renewal_update_in_progress:96});
      const ancona=registry.records.filter(r=>r.authority_key==='ancona');
      assert.equal(ancona.length,577);
      assert.equal(ancona.filter(r=>r.source_key==='ancona-combined').length,577);
      assert.deepEqual(statusCounts(ancona),{listed:331,other_or_unknown:1,pending:145,renewal_update_in_progress:100});
      const bari=registry.records.filter(r=>r.authority_key==='bari');
      assert.equal(bari.length,1670);
      assert.equal(bari.filter(r=>r.source_key==='bari-listed').length,1065);
      assert.equal(bari.filter(r=>r.source_key==='bari-applicants').length,605);
      assert.deepEqual(statusCounts(bari),{listed:754,pending:605,renewal_update_in_progress:311});
      const innovatec=bari.filter(r=>r.name==='INNOVATEC SRL');
      assert.equal(innovatec.length,1);
      assert.deepEqual(innovatec[0].requested_activities,[]);
      const udine=registry.records.filter(r=>r.authority_key==='udine');
      assert.equal(udine.length,1450);
      assert.equal(udine.filter(r=>r.source_key==='udine-listed').length,1431);
      assert.equal(udine.filter(r=>r.source_key==='udine-applicants').length,19);
      assert.deepEqual(statusCounts(udine),{listed:1187,pending:19,renewal_update_in_progress:244});
      const toson=udine.filter(r=>r.name==='TOSON & TOSON DI TOSON DANIELE & C. S.A.S.');
      assert.equal(toson.length,2);
      const toson5=toson.filter(r=>r.requested_activities.length===1&&r.requested_activities[0]==='Sezione 5');
      const toson10=toson.filter(r=>r.requested_activities.length===1&&r.requested_activities[0]==='Sezione 10');
      assert.equal(toson5.length,1);
      assert.equal(toson5[0].identifier_field_raw,'00152050308');
      assert.deepEqual(toson5[0].identifiers,['00152050308']);
      assert.equal(toson10.length,1);
      assert.equal(toson10[0].identifier_field_raw,'000152050308');
      assert.deepEqual(toson10[0].identifiers,[]);
      const palma=udine.filter(r=>r.name==='IMPERMEABILIZZAZIONI PALMA S.R.L.');
      assert.equal(palma.length,1);
      assert.deepEqual(palma[0].source_fields.expiry_date_raw_variants,['269/01/2027']);
      assert.equal(palma[0].observed_expiry_date,'');
      const bergamo=registry.records.filter(r=>r.authority_key==='bergamo');
      assert.equal(bergamo.length,2046);
      assert.equal(bergamo.filter(r=>r.source_key==='bergamo-listed').length,1434);
      assert.equal(bergamo.filter(r=>r.source_key==='bergamo-applicants').length,612);
      assert.deepEqual(statusCounts(bergamo),{listed:626,pending:612,renewal_update_in_progress:808});
      const barletta=registry.records.filter(r=>r.authority_key==='barletta-andria-trani');
      assert.equal(barletta.length,574);
      assert.equal(barletta.filter(r=>r.source_key==='barletta-andria-trani-listed').length,493);
      assert.equal(barletta.filter(r=>r.source_key==='barletta-andria-trani-applicants').length,81);
      assert.deepEqual(statusCounts(barletta),{listed:437,pending:81,renewal_update_in_progress:56});
      const brindisi=registry.records.filter(r=>r.authority_key==='brindisi');
      assert.equal(brindisi.length,411);
      assert.equal(brindisi.filter(r=>r.source_key==='brindisi-listed').length,385);
      assert.equal(brindisi.filter(r=>r.source_key==='brindisi-applicants').length,26);
      assert.deepEqual(statusCounts(brindisi),{listed:341,pending:26,renewal_update_in_progress:44});
      const cagliari=registry.records.filter(r=>r.authority_key==='cagliari');
      assert.equal(cagliari.length,801);
      assert.equal(cagliari.filter(r=>r.source_key==='cagliari-listed').length,750);
      assert.equal(cagliari.filter(r=>r.source_key==='cagliari-applicants').length,51);
      assert.deepEqual(statusCounts(cagliari),{listed:713,pending:51,renewal_update_in_progress:37});
      const caltanissetta=registry.records.filter(r=>r.authority_key==='caltanissetta');
      assert.equal(caltanissetta.length,806);
      assert.equal(caltanissetta.filter(r=>r.source_key==='caltanissetta-listed').length,518);
      assert.equal(caltanissetta.filter(r=>r.source_key==='caltanissetta-applicants').length,288);
      assert.deepEqual(statusCounts(caltanissetta),{listed:281,other_or_unknown:5,pending:288,renewal_update_in_progress:232});
      const crotone=registry.records.filter(r=>r.authority_key==='crotone');
      assert.equal(crotone.length,505);
      assert.equal(crotone.filter(r=>r.source_key==='crotone-listed').length,325);
      assert.equal(crotone.filter(r=>r.source_key==='crotone-applicants').length,180);
      assert.deepEqual(statusCounts(crotone),{listed:72,pending:180,renewal_update_in_progress:253});
      const campobasso=registry.records.filter(r=>r.authority_key==='campobasso');
      assert.equal(campobasso.length,342);
      assert.equal(campobasso.filter(r=>r.source_key==='campobasso-listed').length,323);
      assert.equal(campobasso.filter(r=>r.source_key==='campobasso-applicants').length,19);
      assert.deepEqual(statusCounts(campobasso),{listed:276,pending:19,renewal_update_in_progress:47});
      assert.ok(campobasso.some(r=>r.identifier_field_raw==='880470703'&&r.identifiers.length===0));
      const brescia=registry.records.filter(r=>r.authority_key==='brescia');
      assert.equal(brescia.length,3334);
      assert.equal(brescia.filter(r=>r.source_key==='brescia-listed').length,2071);
      assert.equal(brescia.filter(r=>r.source_key==='brescia-applicants').length,1263);
      assert.deepEqual(statusCounts(brescia),{listed:1859,pending:1263,renewal_update_in_progress:212});
      assert.equal(brescia.filter(r=>r.name==='EDIL EUROPA S.R.L.').length,1);
      const bolzano=registry.records.filter(r=>r.authority_key==='bolzano-bozen');
      assert.equal(bolzano.length,1222);
      assert.equal(bolzano.filter(r=>r.source_key==='bolzano-bozen-listed').length,871);
      assert.equal(bolzano.filter(r=>r.source_key==='bolzano-bozen-applicants').length,351);
      assert.deepEqual(statusCounts(bolzano),{listed:620,pending:351,renewal_update_in_progress:251});
      assert.equal(bolzano.filter(r=>r.source_fields&&Array.isArray(r.source_fields.expiry_date_raw_variants)&&r.source_fields.expiry_date_raw_variants.includes('16/19/2026')&&r.observed_expiry_date==='').length,1);
      const caserta=registry.records.filter(r=>r.authority_key==='caserta');
      assert.equal(caserta.length,2158);
      assert.equal(caserta.filter(r=>r.source_key==='caserta-listed').length,950);
      assert.equal(caserta.filter(r=>r.source_key==='caserta-applicants').length,1208);
      assert.deepEqual(statusCounts(caserta),{listed:395,other_or_unknown:7,pending:1208,renewal_update_in_progress:548});
      assert.equal(caserta.filter(r=>r.source_fields&&Array.isArray(r.source_fields.application_date_raw_variants)&&r.source_fields.application_date_raw_variants.includes('28/25/2025')&&r.application_date==='').length,1);
      const catania=registry.records.filter(r=>r.authority_key==='catania');
      assert.equal(catania.length,1956);
      assert.equal(catania.filter(r=>r.source_key==='catania-listed').length,1632);
      assert.equal(catania.filter(r=>r.source_key==='catania-applicants').length,324);
      assert.deepEqual(statusCounts(catania),{listed:1281,pending:324,renewal_update_in_progress:351});
      assert.equal(catania.filter(r=>r.source_fields&&Array.isArray(r.source_fields.listing_date_raw_variants)&&r.source_fields.listing_date_raw_variants.includes('16/072026')&&r.observed_listing_date==='').length,1);
      const genova=registry.records.filter(r=>r.authority_key==='genova');
      assert.equal(genova.length,762);
      assert.equal(genova.filter(r=>r.source_key==='genova-listed').length,652);
      assert.equal(genova.filter(r=>r.source_key==='genova-applicants').length,110);
      assert.deepEqual(statusCounts(genova),{listed:528,pending:110,renewal_update_in_progress:124});
      const foggia=registry.records.filter(r=>r.authority_key==='foggia');
      assert.equal(foggia.length,958);
      assert.equal(foggia.filter(r=>r.source_key==='foggia-listed').length,330);
      assert.equal(foggia.filter(r=>r.source_key==='foggia-applicants').length,628);
      assert.deepEqual(statusCounts(foggia),{listed:85,pending:628,renewal_update_in_progress:245});
      const forli=registry.records.filter(r=>r.authority_key==='forli-cesena');
      assert.equal(forli.length,749);
      assert.equal(forli.filter(r=>r.source_key==='forli-cesena-combined').length,749);
      assert.deepEqual(statusCounts(forli),{listed:401,pending:144,renewal_update_in_progress:204});
      const frosinone=registry.records.filter(r=>r.authority_key==='frosinone');
      assert.equal(frosinone.length,1236);
      assert.equal(frosinone.filter(r=>r.source_key==='frosinone-listed').length,761);
      assert.equal(frosinone.filter(r=>r.source_key==='frosinone-applicants').length,475);
      assert.deepEqual(statusCounts(frosinone),{listed:529,pending:475,renewal_update_in_progress:232});
      assert.equal(frosinone.filter(r=>r.source_fields&&Array.isArray(r.source_fields.listing_date_raw_variants)&&r.source_fields.listing_date_raw_variants.includes('30/07/*2026')&&r.observed_listing_date==='').length,1);
      assert.equal(frosinone.filter(r=>r.source_fields&&Array.isArray(r.source_fields.application_date_raw_variants)&&r.source_fields.application_date_raw_variants.includes('13/05/206')&&r.application_date==='').length,1);
      const gorizia=registry.records.filter(r=>r.authority_key==='gorizia');
      assert.equal(gorizia.length,127);
      assert.equal(gorizia.filter(r=>r.source_key==='gorizia-listed').length,117);
      assert.equal(gorizia.filter(r=>r.source_key==='gorizia-applicants').length,10);
      assert.deepEqual(statusCounts(gorizia),{listed:86,pending:10,renewal_update_in_progress:31});
      const napoli=registry.records.filter(r=>r.authority_key==='napoli');
      assert.equal(napoli.length,4830);
      assert.equal(napoli.filter(r=>r.source_key==='napoli-listed').length,2259);
      assert.equal(napoli.filter(r=>r.source_key==='napoli-applicants').length,2571);
      assert.deepEqual(statusCounts(napoli),{cancellation_related:3,listed:792,other_or_unknown:30,pending:2530,rejected_or_denied:52,renewal_update_in_progress:1423});
      assert.equal(napoli.filter(r=>r.source_fields&&Array.isArray(r.source_fields.listing_date_raw_variants)&&r.source_fields.listing_date_raw_variants.includes('14/0319')&&r.observed_listing_date==='').length,1);
      assert.equal(napoli.filter(r=>r.source_fields&&Array.isArray(r.source_fields.expiry_date_raw_variants)&&r.source_fields.expiry_date_raw_variants.some(v=>v.startsWith("Iscrizione valida per la durata dell'amministrazi"))&&r.observed_expiry_date==='').length,7);
      const padova=registry.records.filter(r=>r.authority_key==='padova');
      assert.equal(padova.length,1005);
      assert.equal(padova.filter(r=>r.source_key==='padova-listed').length,831);
      assert.equal(padova.filter(r=>r.source_key==='padova-applicants').length,174);
      assert.deepEqual(statusCounts(padova),{listed:581,pending:174,renewal_update_in_progress:250});
      assert.equal(padova.filter(r=>r.source_fields&&Array.isArray(r.source_fields.expiry_date_raw_variants)&&r.source_fields.expiry_date_raw_variants.includes('46581,00')&&r.observed_expiry_date==='').length,1);
      assert.equal(padova.filter(r=>r.source_fields&&Array.isArray(r.source_fields.expiry_date_raw_variants)&&r.source_fields.expiry_date_raw_variants.includes('8807/2026')&&r.observed_expiry_date==='').length,1);
      assert.equal(padova.filter(r=>r.name==='NON SOLO ZANZARE SRL'&&r.source_key==='padova-applicants').length,1);
      assert.equal(padova.filter(r=>r.name==='CLEAN SRL'&&r.source_key==='padova-applicants'&&r.identifier_field_raw==='02027230289'&&r.application_date==='2026-01-14').length,2);
      const perugia=registry.records.filter(r=>r.authority_key==='perugia');
      assert.equal(perugia.length,2229);
      assert.equal(perugia.filter(r=>r.source_key==='perugia-listed').length,1016);
      assert.equal(perugia.filter(r=>r.source_key==='perugia-applicants').length,1213);
      assert.deepEqual(statusCounts(perugia),{listed:1710,other_or_unknown:1,pending:176,renewal_update_in_progress:342});
      assert.equal(perugia.filter(r=>r.source_key==='perugia-listed'&&r.source_fields&&Array.isArray(r.source_fields.expiry_date_raw_variants)&&r.source_fields.expiry_date_raw_variants.includes('1 8/11/2026')&&r.observed_expiry_date==='').length,1);
      assert.equal(perugia.filter(r=>r.source_key==='perugia-applicants'&&r.name===''&&r.identifier_field_raw==='03522900541').length,1);
      assert.equal(perugia.filter(r=>r.source_key==='perugia-applicants'&&r.name==='BORGIONI PREFABBRICATI S.R.L.'&&r.source_status==='other_or_unknown'&&r.outcome_raw==='25/03/2026').length,1);
      const trento=registry.records.filter(r=>r.authority_key==='trento');
      assert.equal(trento.length,1464);
      assert.equal(trento.filter(r=>r.source_key==='trento-listed').length,1366);
      assert.equal(trento.filter(r=>r.source_key==='trento-applicants').length,98);
      assert.deepEqual(statusCounts(trento),{listed:699,pending:98,renewal_update_in_progress:667});
      assert.equal(trento.filter(r=>r.source_key==='trento-listed'&&r.name==='BUTTERINI PIETRO TRASPORTI S.R.L.'&&r.identifier_field_raw==='006281590229'&&r.identifiers.length===0).length,1);
      assert.equal(trento.filter(r=>r.source_key==='trento-listed'&&r.source_fields&&Array.isArray(r.source_fields.listing_date_raw_variants)&&r.source_fields.listing_date_raw_variants.includes('14.04.206')&&r.observed_listing_date==='').length,1);
      assert.equal(trento.filter(r=>r.source_key==='trento-applicants'&&r.name==='ROMANI DE MOLL S.R.L. IMPRESA SOCIALE'&&r.application_date==='2026-06-29'&&r.source_fields.application_date_raw_variants.includes('29.06.2026 (integrata il 02.07.2026)')).length,1);
      const lodi=registry.records.filter(r=>r.authority_key==='lodi');
      assert.equal(lodi.length,173);
      assert.equal(lodi.filter(r=>r.source_key==='lodi-listed').length,169);
      assert.equal(lodi.filter(r=>r.source_key==='lodi-applicants').length,4);
      assert.deepEqual(statusCounts(lodi),{listed:146,pending:2,rejected_or_denied:2,renewal_update_in_progress:23});
      assert.deepEqual(lodi.filter(r=>r.source_status==='rejected_or_denied').map(r=>r.decision_date).sort(),['2021-06-17','2022-11-17']);
      const roma=registry.records.filter(r=>r.authority_key==='roma');
      assert.equal(roma.length,4428);
      assert.equal(roma.filter(r=>r.source_key==='roma-listed').length,2169);
      assert.equal(roma.filter(r=>r.source_key==='roma-applicants').length,2259);
      assert.deepEqual(statusCounts(roma),{listed:1215,pending:2256,renewal_update_in_progress:957});
      assert.equal(new Set(roma.map(r=>r.record_locator)).size,4428);
      const pisa=registry.records.filter(r=>r.authority_key==='pisa');
      assert.equal(pisa.length,449);
      assert.equal(pisa.filter(r=>r.source_key==='pisa-listed').length,398);
      assert.equal(pisa.filter(r=>r.source_key==='pisa-applicants').length,18);
      assert.equal(pisa.filter(r=>r.source_key==='pisa-renewal-update').length,33);
      assert.deepEqual(statusCounts(pisa),{listed:398,pending:18,renewal_update_in_progress:33});
      assert.equal(new Set(pisa.map(r=>r.record_locator)).size,449);
      assert.equal(pisa.filter(r=>r.source_key==='pisa-listed'&&r.identifiers.length>0).length,397);
      assert.equal(pisa.filter(r=>r.source_key==='pisa-applicants'&&r.identifiers.length>0).length,18);
      assert.equal(pisa.filter(r=>r.source_key==='pisa-renewal-update'&&r.identifiers.length>0).length,33);
      assert.equal(pisa.filter(r=>r.name==='ROHDE NIELSEN A/S'&&r.source_key==='pisa-listed'&&r.identifiers.length===0).length,1);
      const catanzaro=registry.records.filter(r=>r.authority_key==='catanzaro');
      assert.equal(catanzaro.length,887);
      assert.equal(catanzaro.filter(r=>r.source_key==='catanzaro-listed').length,610);
      assert.equal(catanzaro.filter(r=>r.source_key==='catanzaro-applicants').length,277);
      assert.deepEqual(statusCounts(catanzaro),{listed:377,pending:277,renewal_update_in_progress:233});
      assert.equal(new Set(catanzaro.map(r=>r.record_locator)).size,887);
      assert.equal(catanzaro.filter(r=>r.source_key==='catanzaro-listed'&&r.identifiers.length>0).length,601);
      assert.equal(catanzaro.filter(r=>r.source_key==='catanzaro-applicants'&&r.identifiers.length>0).length,272);
      assert.equal(catanzaro.filter(r=>r.source_key==='catanzaro-listed'&&Array.isArray(r.source_fields?.physical_locators)).length,610);
      assert.equal(catanzaro.filter(r=>r.source_key==='catanzaro-applicants'&&typeof r.source_fields?.physical_locator==='string').length,277);
      assert.equal(catanzaro.filter(r=>r.source_key==='catanzaro-applicants'&&r.source_fields?.application_date_raw==='1/8/12/2025'&&r.application_date==='').length,1);
      const lecco=registry.records.filter(r=>r.authority_key==='lecco');
      assert.equal(lecco.length,256);
      assert.equal(lecco.filter(r=>r.source_key==='lecco-listed').length,230);
      assert.equal(lecco.filter(r=>r.source_key==='lecco-applicants').length,26);
      assert.deepEqual(statusCounts(lecco),{listed:201,pending:22,rejected_or_denied:4,renewal_update_in_progress:29});
      assert.equal(new Set(lecco.map(r=>r.record_locator)).size,256);
      assert.equal(lecco.filter(r=>r.source_key==='lecco-listed'&&r.identifiers.length>0).length,228);
      assert.equal(lecco.filter(r=>r.source_key==='lecco-applicants'&&r.identifiers.length>0).length,26);
      const termoidraulica=lecco.filter(r=>r.source_key==='lecco-listed'&&r.name==='Termoidraulica');
      assert.equal(termoidraulica.length,1);
      assert.equal(termoidraulica[0].identifier_field_raw,'035180050137');
      assert.deepEqual(termoidraulica[0].identifiers,[]);
      assert.deepEqual(termoidraulica[0].requested_activities,[]);
      const edilnord=lecco.filter(r=>r.source_key==='lecco-applicants'&&r.identifier_field_raw==='01882770132');
      assert.equal(edilnord.length,3);
      assert.deepEqual(edilnord.map(r=>r.application_date).sort(),['2013-12-12','2016-01-29','2017-04-18']);
      const torino=registry.records.filter(r=>r.authority_key==='torino');
      assert.equal(torino.length,1663);
      assert.equal(torino.filter(r=>r.source_key==='torino-listed').length,1501);
      assert.equal(torino.filter(r=>r.source_key==='torino-applicants').length,162);
      assert.deepEqual(statusCounts(torino),{listed:1237,pending:162,renewal_update_in_progress:264});
      assert.equal(new Set(torino.map(r=>r.record_locator)).size,1663);
      assert.equal(torino.filter(r=>r.source_key==='torino-listed'&&r.identifiers.length>0).length,1496);
      assert.equal(torino.filter(r=>r.source_key==='torino-applicants'&&r.identifiers.length>0).length,162);
      assert.equal(torino.filter(r=>r.source_key==='torino-listed'&&r.application_date==='').length,1241);
      const potenza=registry.records.filter(r=>r.authority_key==='potenza');
      assert.equal(potenza.length,1035);
      assert.equal(potenza.filter(r=>r.source_key==='potenza-combined').length,1035);
      assert.deepEqual(statusCounts(potenza),{listed:216,pending:376,renewal_update_in_progress:443});
      assert.equal(new Set(potenza.map(r=>r.record_locator)).size,1035);
      assert.equal(potenza.filter(r=>r.identifiers.length>0).length,1034);
      assert.equal(potenza.filter(r=>r.identifier_field_raw&&r.identifiers.length===0).length,1);
      assert.equal(potenza.filter(r=>r.application_date!=='').length,1035);
      assert.equal(potenza.filter(r=>r.observed_listing_date!=='').length,659);
      assert.equal(potenza.filter(r=>r.observed_expiry_date!=='').length,659);
      assert.equal(potenza.filter(r=>r.requested_activities.length>0).length,0);
      assert.ok(potenza.every(r=>r.parser_name==='potenza_combined'&&r.parser_version==='2'));
      assert.ok(potenza.every(r=>r.source_fields.physical_locator.startsWith('source-id:')));
      assert.ok(potenza.every(r=>Array.isArray(r.source_fields.notes)));
      assert.equal(potenza.filter(r=>r.source_fields.notes.length>0).length,1);
      const gap=potenza.filter(r=>r.source_fields.physical_locator==='source-id:903');
      assert.equal(gap.length,1);
      assert.equal(gap[0].name,'GAP S.R.L.S.');
      assert.equal(gap[0].source_status,'renewal_update_in_progress');
      assert.equal(gap[0].observed_listing_date,'2024-11-28');
      assert.equal(gap[0].observed_expiry_date,'2025-11-28');
      assert.equal(gap[0].source_fields.in_aggiornamento,'1');
      const scavone=potenza.filter(r=>r.source_fields.physical_locator==='source-id:656');
      assert.equal(scavone.length,1);
      assert.equal(scavone[0].name,'SCAVONE & C. S.R.L.');
      assert.equal(scavone[0].identifier_field_raw,'01652690767');
      assert.equal(scavone[0].source_status,'pending');
      assert.equal(scavone[0].application_date,'2026-09-16');
      const malaspina=potenza.filter(r=>r.source_fields.physical_locator==='source-id:359');
      assert.equal(malaspina.length,1);
      assert.equal(malaspina[0].name,'MALASPINA S.R.L.');
      assert.equal(malaspina[0].source_status,'renewal_update_in_progress');
      assert.equal(malaspina[0].observed_listing_date,'2018-10-18');
      assert.equal(malaspina[0].observed_expiry_date,'2026-10-18');
      assert.equal(malaspina[0].source_fields.in_aggiornamento,'1');
      const sassari=registry.records.filter(r=>r.authority_key==='sassari');
      assert.equal(sassari.length,478);
      assert.equal(sassari.filter(r=>r.source_key==='sassari-combined').length,478);
      assert.deepEqual(statusCounts(sassari),{expired_observed:1,listed:335,other_or_unknown:1,pending:129,renewal_update_in_progress:12});
      assert.equal(new Set(sassari.map(r=>r.record_locator)).size,478);
      assert.equal(sassari.filter(r=>r.identifiers.length>0).length,472);
      assert.equal(sassari.filter(r=>r.identifier_field_raw&&r.identifiers.length===0).length,6);
      assert.ok(sassari.every(r=>r.requested_activities.length>0));
      assert.ok(sassari.every(r=>r.parser_name==='sassari_combined'&&r.parser_version==='1'));
      assert.ok(sassari.every(r=>r.source_fields.physical_locator.startsWith('Foglio1!')));
      const mia=sassari.filter(r=>r.name==='M.I.A. SRL');
      assert.equal(mia.length,1);
      assert.equal(mia[0].source_fields.application_date_raw,'129.01.2025');
      assert.equal(mia[0].application_date,'');
      const descari=sassari.filter(r=>r.name==='DE.SCA.RI DEL GEOM. CALIA GIANLUCA');
      assert.equal(descari.length,1);
      assert.equal(descari[0].registered_office,'CLAGLC74B11E736M');
      assert.equal(descari[0].identifier_field_raw,'OLBIA');
      const milano=registry.records.filter(r=>r.authority_key==='milano');
      assert.equal(milano.length,2611);
      assert.equal(milano.filter(r=>r.source_key==='milano-combined').length,2611);
      assert.deepEqual(statusCounts(milano),{listed:940,pending:1157,renewal_update_in_progress:514});
      assert.equal(new Set(milano.map(r=>r.record_locator)).size,2611);
      assert.equal(milano.filter(r=>r.identifiers.length>0).length,2611);
      assert.ok(milano.every(r=>r.requested_activities.length>0));
      assert.equal(milano.filter(r=>r.application_date!=='').length,1157);
      assert.equal(milano.filter(r=>r.observed_listing_date!=='').length,940);
      assert.equal(milano.filter(r=>r.observed_expiry_date!=='').length,940);
      assert.equal(Math.max(...milano.filter(r=>r.application_date).map(r=>Date.parse(r.application_date))),Date.parse('2026-09-17'));
      const currentMilano=Object.fromEntries(milano.map(r=>[r.identifier_field_raw,r]));
      for(const k of ['06543250960','12134200968']){assert.equal(currentMilano[k].source_status,'pending');assert.equal(currentMilano[k].application_date,'2026-09-17');}
      for(const k of ['12957130961','13540670968','14580020965']) assert.equal(currentMilano[k],undefined);
      for(const k of ['01081040154','02004400996','04214900161','05561460824','05696960961','06785160968','08530830960','10553180968','10753650018','12654640965','13163200960']) assert.equal(currentMilano[k].source_status,'listed');
      for(const k of ['01843860543','08402360963','09406080961','11572370960']) assert.equal(currentMilano[k].source_status,'renewal_update_in_progress');
      assert.ok(milano.every(r=>Array.isArray(r.source_fields.notes)));
      const notedMilano=milano.filter(r=>r.source_fields.notes.length>0);
      assert.equal(notedMilano.length,1);
      assert.equal(notedMilano[0].name,'COMOTER SRL');
      assert.deepEqual(notedMilano[0].source_fields.notes,['Misura di prevenzione collaborativa ex art. 94 bis D.lgs.159/2011 in data 18/04/2024, per la durata di un anno']);
      assert.ok(milano.every(r=>r.source_fields.sections.length===r.source_fields.physical_locators.length));
      const modena=registry.records.filter(r=>r.authority_key==='modena');
      assert.equal(modena.length,3792);
      assert.equal(modena.filter(r=>r.source_key==='modena-provincial-listed').length,1181);
      assert.equal(modena.filter(r=>r.source_key==='modena-provincial-applicants').length,502);
      assert.equal(modena.filter(r=>r.source_key==='modena-post-sisma-listed').length,1679);
      assert.equal(modena.filter(r=>r.source_key==='modena-post-sisma-applicants').length,430);
      assert.deepEqual(statusCounts(modena),{listed:1560,pending:932,renewal_update_in_progress:1300});
      assert.equal(new Set(modena.map(r=>r.record_locator)).size,3792);
      assert.equal(modena.filter(r=>r.identifiers.length>0).length,3751);
      assert.equal(modena.filter(r=>r.identifier_field_raw&&r.identifiers.length===0).length,41);
      assert.ok(modena.every(r=>r.requested_activities.length>0));
      assert.ok(modena.every(r=>['modena_listed','modena_applicants'].includes(r.parser_name)&&r.parser_version==='1'));
      assert.ok(modena.every(r=>r.source_fields.sections.length>0&&r.source_fields.physical_locators.length>0));
      const pm=crotone.filter(r=>r.name==='PM COSTRUZIONI S.R.L.');
      assert.ok(pm.some(r=>r.identifier_field_raw==='0330033796'&&r.identifiers.length===0));
      const a2g=caltanissetta.filter(r=>r.name==='A2G CONSTRUCTION SRL');
      assert.equal(a2g.length,1);
      assert.equal(a2g[0].identifier_field_raw,'020826508502');
      assert.deepEqual(a2g[0].identifiers,[]);
      const aeffe=cagliari.filter(r=>r.name==='AEFFE di Farci Alessandro');
      assert.equal(aeffe.length,1);
      assert.equal(aeffe[0].identifier_field_raw,'0336817853');
      assert.deepEqual(aeffe[0].identifiers,[]);
      assert.deepEqual(aeffe[0].requested_activities,['Sezione 1','Sezione 5']);
      const lapignola=cagliari.filter(r=>r.name==='La Pignola S.r.l.');
      assert.equal(lapignola.length,1);
      assert.equal(lapignola[0].identifier_field_raw,'3814850925');
      assert.deepEqual(lapignola[0].identifiers,[]);
      const collu=cagliari.filter(r=>r.name==='Collu Giuliano Impresa Individuale');
      assert.equal(collu.length,1);
      assert.equal(collu[0].registered_office,'');
      const bars=page.locator('#view-statistics .stat-table').first().locator('.stat-number');
      assert.equal((await bars.allTextContents()).reduce((n,t)=>n+numeric(t),0),stats.total);
      assert.equal(await page.locator('#view-statistics a').count(),new Set(stats.latest.map(r=>JSON.stringify([r.source_key,r.reference_date,r.capture_sha256]))).size);
      await page.locator('#stats-authority').selectOption('alessandria');
      const alessandriaStats=publicStatistics(registry.records,'alessandria');
      assert.equal(alessandriaStats.total,434);
      assert.equal((await bars.allTextContents()).reduce((n,t)=>n+numeric(t),0),alessandriaStats.total);
      await page.getByRole('button',{name:'Registro',exact:true}).click();
      await page.locator('#reg-latest').uncheck();
      await page.locator('#reg-authority').selectOption('alessandria');
      await page.locator('#reg-status').selectOption('pending');
      assert.equal(numeric(await page.locator('#view-registry .section-title').last().innerText()),alessandria.filter(r=>r.source_status==='pending').length);
      await page.getByRole('button',{name:'Statistiche',exact:true}).click();
      await page.locator('#stats-authority').selectOption('cosenza');
      const cosenza=publicStatistics(registry.records,'cosenza');
      assert.equal((await bars.allTextContents()).reduce((n,t)=>n+numeric(t),0),cosenza.total);
      const pendingBar=page.locator('#view-statistics .stat-table').first().locator('[data-stat-status="pending"]');
      const pendingCount=numeric(await pendingBar.innerText());
      await pendingBar.focus();
      await pendingBar.press('Enter');
      assert.equal(await page.locator('#reg-latest').isChecked(),true);
      assert.equal(await page.locator('#reg-authority').inputValue(),'cosenza');
      assert.equal(await page.locator('#reg-status').inputValue(),'pending');
      assert.equal(numeric(await page.locator('#view-registry .section-title').last().innerText()),pendingCount);
      await page.getByRole('button',{name:'Statistiche',exact:true}).click();
      const bolognaBar=page.locator('#view-statistics .stat-table').nth(1).locator('[data-stat-authority="bologna"][data-stat-status="pending"]');
      const bolognaCount=numeric(await bolognaBar.innerText());
      assert.equal(bolognaCount,stats.latest.filter(r=>r.authority_key==='bologna'&&r.source_status==='pending').length);
      await bolognaBar.click();
      assert.equal(numeric(await page.locator('#view-registry .section-title').last().innerText()),bolognaCount);
      await page.locator('#reg-latest').uncheck();
      await page.locator('#reg-status').selectOption('listed');
      await page.getByRole('button',{name:'Registro',exact:true}).click();
      await page.locator('#reg-authority').selectOption('bologna');
      await page.locator('#reg-register').selectOption('bologna-post-sisma');
      assert.ok((await page.locator('#view-registry tbody').innerText()).includes('White List post-sisma'));
      assert.deepEqual(errors,[]);
      await page.close();
      console.log(`Public registry, source links, all sections and layout passed at ${width}px`);
    }
  } finally {await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});